{
  "openapi": "3.1.0",
  "info": {
    "title": "API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}/postings": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Posting"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "title": "Honda civic",
                        "Description": "Good condition car",
                        "Category": "Cars",
                        "Location": "Oulu",
                        "Images": "string",
                        "Asking price": "100€",
                        "date of posting": "20-11-2020",
                        "Delivery Type": "Shipping",
                        "Name": "Jaska Jokunen",
                        "phone number": 442356232,
                        "email": "jaska.jokunen@hotmail.com"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Posting not found Not Found"
          }
        },
        "operationId": "get-users-postings",
        "description": "Retrieve the information of the users posting",
        "parameters": []
      },
      "patch": {
        "summary": "Update Posting Information",
        "operationId": "patch-users-postings",
        "responses": {
          "200": {
            "description": "Posting Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Posting"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "title": "Honda civic",
                      "Description": "Good condition car",
                      "Category": "Cars",
                      "Location": "Oulu",
                      "Images": "string",
                      "Asking price": "100€",
                      "date of posting": "20-11-2020",
                      "Delivery Type": "Shipping",
                      "Name": "Jaska Jokunen",
                      "phone number": 442356232,
                      "email": "jaska.jokunen@hotmail.com"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Posting Not Found"
          }
        },
        "description": "Update the information of an existing posting.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Posting"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "title": "Honda civic",
                    "Description": "Good condition car",
                    "Category": "Cars",
                    "Location": "Oulu",
                    "Images": "string",
                    "Asking price": "100€",
                    "date of posting": "11.11.2020",
                    "Delivery Type": "Shipping",
                    "Name": "Jaska Jokunen",
                    "phone number": 442356232,
                    "email": "jaska.jokunen@hotmail.com"
                  }
                }
              }
            }
          },
          "description": "Patch posting properties to update."
        }
      },
      "delete": {
        "summary": "",
        "operationId": "delete-users-userId-postings",
        "responses": {
          "200": {
            "description": "Posting has been deleted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Posting"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "title": "Honda civic",
                      "Description": "Good condition car",
                      "Category": "Cars",
                      "Location": "Oulu",
                      "Images": "string",
                      "Asking price": "100€",
                      "date of posting": "20-11-2020",
                      "Delivery Type": "Shipping",
                      "Name": "Jaska Jokunen",
                      "phone number": 442356232,
                      "email": "jaska.jokunen@hotmail.com"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Posting Not Found"
          }
        },
        "description": "Delete a posting"
      }
    },
    "/register": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": "12",
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18",
                      "password": "BobFellowpassword123"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  },
                  "password": {
                    "type": [
                      "string",
                      "number"
                    ]
                  },
                  "phone number": {
                    "type": "number"
                  },
                  "location": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "string",
                    "lastName": "string",
                    "email": "string",
                    "dateOfBirth": "2019-08-24",
                    "password": "string",
                    "phone number": 0,
                    "location": "string"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user.",
        "parameters": []
      },
      "parameters": []
    },
    "/users/{userId}/create-posting": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "userId",
          "in": "path",
          "required": true
        }
      ],
      "post": {
        "summary": "",
        "operationId": "post-users-userId-create-posting",
        "responses": {
          "200": {
            "description": "Posting created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Posting"
                }
              }
            }
          },
          "400": {
            "description": "Missing information"
          }
        },
        "description": "Create a posting for the user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {
                "example-1": {
                  "value": {}
                }
              }
            },
            "application/javascript": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": ""
        }
      }
    },
    "/postings": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "Postings found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Posting"
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "title": "Honda civic",
                        "Description": "Good condition car",
                        "Category": "Cars",
                        "Location": "Oulu",
                        "Images": "string.jpg",
                        "Asking price": "100€",
                        "date of posting": "20-11-2020",
                        "Delivery Type": "Shipping",
                        "Name": "Jaska Jokunen",
                        "phone number": 442356232,
                        "email": "jaska.jokunen@hotmail.com"
                      },
                      {
                        "title": "Honda civic",
                        "Description": "bad condition car",
                        "Category": "Cars",
                        "Location": "Helsinki",
                        "Images": "string2.jpg",
                        "Asking price": "100€",
                        "date of posting": "2-12-2021",
                        "Delivery Type": "Shipping",
                        "Name": "Josh Smith",
                        "phone number": 204032211,
                        "email": "Josh.Smith@email.com"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "POSTINGS NOT FOUND"
          }
        },
        "operationId": "get-postings",
        "description": "Postings of the site"
      }
    },
    "/login": {
      "post": {
        "summary": "",
        "operationId": "post-login",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "id": "123",
                      "password": "alicesmith231",
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": [
                        "string",
                        "number"
                      ]
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "email": "alice.smith@gmail.com",
                      "password": "alicesmith321"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Posts the email and the password"
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "Users information",
        "examples": [
          {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique identifier for the given user."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": [
              "string",
              "number"
            ]
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the user's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          },
          "phone number": {
            "type": "number"
          },
          "location": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "password",
          "emailVerified"
        ]
      },
      "Posting": {
        "title": "Posting",
        "type": "object",
        "x-internal": false,
        "description": "PostingId will be given in the API",
        "examples": [
          {
            "title": "Honda civic",
            "Description": "Good condition car",
            "Category": "Cars",
            "Location": "Oulu",
            "Images": "string",
            "Asking price": "100€",
            "date of posting": "11.11.2020",
            "Delivery Type": "Shipping",
            "Name": "Jaska Jokunen",
            "phone number": 442356232,
            "email": "jaska.jokunen@hotmail.com"
          }
        ],
        "properties": {
          "postingId": {
            "type": "string"
          },
          "title": {
            "type": "string",
            "example": "Honda civic",
            "description": "The title of the product"
          },
          "Description": {
            "type": "string",
            "example": "Good condition car",
            "description": "description of the product"
          },
          "Category": {
            "type": "string",
            "example": "Cars",
            "description": "category of the product"
          },
          "Location": {
            "type": "string",
            "example": "Oulu",
            "description": "Location of the seller/product"
          },
          "Images": {
            "type": "string",
            "description": "an image of the product"
          },
          "Asking price": {
            "type": "string",
            "example": "100€",
            "description": "the priceof the product"
          },
          "date of posting": {
            "type": "string",
            "example": "11.11.2020",
            "description": "date of the posting"
          },
          "Delivery Type": {
            "type": "string",
            "example": "Shipping",
            "description": "how is it delivered ex. Shipping/Pickup"
          },
          "Name": {
            "type": "string",
            "example": "Jaska Jokunen",
            "description": "Name of the seller"
          },
          "phone number": {
            "type": "number",
            "example": 442356232,
            "description": "phone number of the seller"
          },
          "email": {
            "type": "string",
            "example": "jaska.jokunen@hotmail.com",
            "format": "email",
            "description": "email of the seller"
          }
        },
        "required": [
          "title",
          "Description",
          "Category",
          "Location",
          "Asking price",
          "Delivery Type",
          "Name",
          "phone number",
          "email"
        ]
      }
    }
  }
}